#!/usr/bin/expect -f
set timeout 30
spawn bash -c "source ~/.nvm/nvm.sh && npx eas-cli credentials -p android"

expect "Which build profile do you want to configure?"
send "\033\[B\033\[B\r"

expect "What do you want to do?"
# Default is "Keystore: Manage everything needed to build your project"
send "\r"

expect "What do you want to do?"
# Default is "Set up a new keystore"
# "Change default keystore"
# "Download existing keystore" (needs 2 down arrows)
send "\033\[B\033\[B\r"

expect eof
